org: chauhansneha
service: task1-python

provider:
  name: aws
  runtime: python3.8
  region: ap-south-1
  endpoint: http://localhost:4566
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

plugins:
  - serverless-offline
  - serverless-localstack

custom:
  localstack:
    stages:
      - local

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: post
